#!/bin/bash


OUT=/home/scratch60/lbuzzo/RTC/outputs/save_legacy_5

make processSample INPUT_FILE=/home/projects/local_collab/gh_RTC_simulation/genomes/g1/g1_8x.bam.sorted.bam OUTPUT_DIR=$OUT SORTED=TRUE &
make processSample INPUT_FILE=/home/projects/local_collab/gh_RTC_simulation/genomes/g2/g2_8x.bam.sorted.bam OUTPUT_DIR=$OUT SORTED=TRUE &
make processSample INPUT_FILE=/home/projects/local_collab/gh_RTC_simulation/genomes/g3/g3_8x.bam.sorted.bam OUTPUT_DIR=$OUT SORTED=TRUE &
make processSample INPUT_FILE=/home/projects/local_collab/gh_RTC_simulation/genomes/g4/g4_8x.bam.sorted.bam OUTPUT_DIR=$OUT SORTED=TRUE &
make processSample INPUT_FILE=/home/projects/local_collab/gh_RTC_simulation/genomes/g5/g5_8x.bam.sorted.bam OUTPUT_DIR=$OUT SORTED=TRUE &

wait

make mergeCall OUTPUT_DIR=$OUT -j 4

../../miscellaneous/counter.sh $OUT > $OUT/counts.txt
