#!/bin/bash

clear
make mergeCall REFERENCE_GENOME_FASTA=/home/genomes/Homo_sapiens/hg38/toBWA/hg38.fa OUTPUT_DIR=./ghmake_8 -j

#make mergeCall REFERENCE_GENOME_FASTA=/home/genomes/Homo_sapiens/hg38/toBWA/hg38.fa OUTPUT_DIR=../ghmake_40 -j

